// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "18be25e7-da21-463b-b1ae-c8f04d3eecda";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onEnableLEDChange();

float hpa;
float hum;
float tmp;
int hpa_scale;
bool enableLED;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(hpa, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(hum, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(tmp, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(hpa_scale, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(enableLED, READWRITE, 1 * SECONDS, onEnableLEDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
